<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="akka" nsURI="http://assignmentsystem.ntnu.no/akka/1.0" nsPrefix="no.ntnu.assignmentsystem">
  <eClassifiers xsi:type="ecore:EClass" name="EditorServices" abstract="true" interface="true"
      eSuperTypes="#//RunMainServices #//RunTestsServices #//SourceCodeServices #//CodeCompletionServices">
    <eOperations name="isReady" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//TestResult.Status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestResult.Status">
    <eLiterals name="OK"/>
    <eLiterals name="Failed"/>
    <eLiterals name="Ignored"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemMarkersFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problemMarkers" upperBound="-1"
        eType="#//ProblemMarker" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemMarker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProblemMarker.Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProblemMarker.Type">
    <eLiterals name="Error"/>
    <eLiterals name="Warning"/>
    <eLiterals name="Information"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCompletionProposal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunMainServices" abstract="true" interface="true">
    <eOperations name="runMain" eType="#//RunMainResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunTestsServices" abstract="true" interface="true">
    <eOperations name="runTests" eType="#//RunTestsResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeServices" abstract="true"
      interface="true">
    <eOperations name="updateSourceCode" unique="false" eType="#//ErrorCheckingResult">
      <eParameters name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sourceCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCompletionServices" abstract="true"
      interface="true">
    <eOperations name="codeCompletion" eType="#//CodeCompletionResult">
      <eParameters name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunMainResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunTestsResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testResults" upperBound="-1"
        eType="#//TestResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorCheckingResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ProblemMarkersFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCompletionResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposals" upperBound="-1"
        eType="#//CodeCompletionProposal" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
