<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="akka" nsURI="http://assignmentsystem.ntnu.no/akka/1.0" nsPrefix="no.ntnu.assignmentsystem">
  <eClassifiers xsi:type="ecore:EClass" name="Editor" abstract="true" interface="true">
    <eOperations name="notifyOnReady"/>
    <eOperations name="runMain"/>
    <eOperations name="runTests"/>
    <eOperations name="updateSourceCode">
      <eParameters name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sourceCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="codeCompletion">
      <eParameters name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorDelegate" abstract="true" interface="true">
    <eOperations name="ready"/>
    <eOperations name="runMainResult">
      <eParameters name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="runTestsResult">
      <eParameters name="testResults" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    </eOperations>
    <eOperations name="errorCheckingResult">
      <eParameters name="problemMarkersFiles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    </eOperations>
    <eOperations name="codeCompletionResult">
      <eParameters name="proposals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//TestResult.Status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestResult.Status">
    <eLiterals name="OK"/>
    <eLiterals name="Failed"/>
    <eLiterals name="Ignored"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemMarkersFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problemMarkers" upperBound="-1"
        eType="#//ProblemMarker" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemMarker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProblemMarker.Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProblemMarker.Type">
    <eLiterals name="Error"/>
    <eLiterals name="Warning"/>
    <eLiterals name="Information"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCompletionProposal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
